---
language: python

python:
  - "2.7"
  - "3.3"
virtualenv:
  system_site_packages: true

sudo: required

notifications:
  email: change

env:
  - RUN_INSTRUMENT=bc8n856M4k

install:
  # Install corr2, casperfpga and nosekatreport dependencies manually
  - pip install -r https://raw.githubusercontent.com/ska-sa/mkat_fpga_tests/devel/pip-dev-requirements.txt

script:
  - source .bash_configs
  - bash -x 1.install_dependencies.sh && bash -x 2.verify_dependencies.sh
