---
language: python

python:
  - "2.7"
  - "3.6"
virtualenv:
  system_site_packages: true

sudo: required

notifications:
  email: change

env:
  - RUN_INSTRUMENT=bc8n856M4k

install:
  - sudo apt-get install -y shellcheck

script:
  - source .bash_configs
  - bash -x 1.install_dependencies.sh && bash -x 2.verify_dependencies.sh
